[project]
name = "agent-rag-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "dbutils>=3.1.2",
    "fastapi>=0.141.1",
    "loguru>=0.7.3",
    "markdown>=3.10.3",
    "minio>=7.2.20",
    "pydantic-settings>=2.15.0",
    "pymilvus>=3.0.1",
    "pymysql>=1.2.0",
    "pypdf>=6.16.1",
    "python-docx>=1.2.0",
    "python-multipart>=0.0.32",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "uvicorn[standard]>=0.52.3",
    "xhtml2pdf>=0.2.17",
]
